### ISSUE TITLE
We need a name

### ISSUE THREAD

**Issue by kris-nova** [opna/conf#1]
So `ConfConf` is cool but it's been done before. 

We need a catchy name that captures the spirit of the event, and we need the following for the event.

 - Twitter handle
 - Domain (.io, .org, whatever)
 - GitHub org 

If anyone has ideas please add them below in a comment. We can :+1: or :-1:  as a community.

If you really think your idea is great, please grab the github org or twiter handle, and I am sure that will be a compelling argument for your name. If you need me to buy the domain just hit me up. 

Once we decide, and have a twitter handle, and github org and name, we can start moving things over to the next step and opening a CFP.

**Comment by shanselman** [comment]
RATlLJÓSTCONF - "enough light to navigate" in Icelandic

**Comment by cczona** [comment]
Neat, @shanselman! What's Icelandic for something like partnership or collaboration?

**Comment by agocs** [comment]
I worry that an Icelandic name might make it hard for non-Icelandic-speakers to figure out what we're all about. Thoughts?

**Comment by shanselman** [comment]
@cczona Samstarf

**Comment by shanselman** [comment]
@agocs if it's a "pronounce it like it looks" then I think it's ok. If it's Svalbarðsstrandarhreppur, then ya, that's a problem ;)

**Comment by kris-nova** [comment]
Hvað um `opnaconf`? 

> What about OpenConf?

It's close to english, it describes the event, it's still Icelandic, and `opna` can be an acronym if needed

> Open Presentations for New Audiences 

for example.

**Comment by shanselman** [comment]
If it's not taken, I love that.

**Comment by kris-nova** [comment]
So I just bought `opnaconf.com` and we have [@opnaconf](https://twitter.com/opnaconf) (thanks doctor tigums) and I will be porting this over to github.com/opna/conf
